colanguage: php

php:
  - 7.3
  - 7.4

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer validate --strict
  - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit -v
